//this page changes stuff for ALL pages

import "../globals.css";

export const metadata = {
  title: 'My Next/Sanity Page',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}