import Link from 'next/link'
import '../globals.css'
import type { Metadata } from 'next'
import { getPages } from '@/sanity/sanity-utils'

//this page changes stuff for ALL pages

export const metadata: Metadata = {
  title: 'My Next/Sanity Page',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10 bg-pink-200 '>
        <header className='flex items-center justify-between'>
          <Link href="/" className='bg-gradient-to-r from-yellow-400 via-lime-500 to-green-600 bg-clip-text text-transparent text-2xl'>
            TimmyPage
          </Link>
          <div className='flex items-center gap-5'>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='hover:underline'>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
      </body>
      <body>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
