import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'

//this page changes stuff for ALL pages

export const metadata: Metadata = {
  title: 'My Next/Sanity Page',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10 bg-pink-200 '>
        <header>
          <Link href="/" className='bg-gradient-to-r from-yellow-400 via-lime-500 to-green-600 bg-clip-text text-transparent text-2xl'>
            TimmyPage
          </Link>
        </header>
      </body>
      <body>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
